### ISSUE TITLE
Not capturing click_on or assertions hot keys

### ISSUE THREAD

**Issue by drnic** [bullet-train-co/magic_test#12]
On the plus side, `flush` is outputting `fill_in` actions. But it is not outputting the `click_on` links I clicked.

I am guessing the issue is with the javascript and its relationship with turbolinks (and newer turbo).

I'm also not able to activate the CTRL+SHIFT+A feature to assert text.

Perhaps fixed by #2; or need some turbo(links) love to incorporate jquery into turbolinks enhanced pages. Or its something else.

**Comment by andrewculver** [comment]
@drnic I did all my last-mile testing on Turbolinks, but I'll take it for a spin on our Turbo branch as well. Really appreciate these issues, they're a huge help. Obviously I wish you were having the pure magic experience, but you're certainly helping us create that for more folks in the future. 🙏

**Comment by tleish** [comment]
Worked for me with Turbo.

**Comment by drnic** [comment]
Thanks @tleish @andrewculver I'll try harder to debug.

**Comment by tleish** [comment]
@drnic - I thought you were referring to just turbolinks for the original title.  I just created a ticket (which appears to be a duplicate of your update) here: https://github.com/bullet-train-co/magic_test/issues/14

**Comment by drnic** [comment]
I'll close this issue in lieu of your better #14
