### ISSUE TITLE
Missing Link Click

### ISSUE THREAD

**Issue by tleish** [bullet-train-co/magic_test#14]
When testing this on Devise (with hotwire/turbo), if I click on one of the links (e.g. "Forgot Password"), "click_on" does not register. 

I narrowed it down to:

```javascript
// app/views/magic_test/_javascript_helpers.html
function clickFunction(event) {
  var tagName = event.currentTarget.tagName
```

In the above scenario:
```javascript
event.currentTarget == document
event.target == a[link]
```

Before creating a pull request to fix the bug I need to understand why you chose `event.currentTarget` vs `event.target`.

> **Event.currentTarget**
> The currentTarget read-only property of the Event interface identifies the current target for the event, as the event traverses the DOM. It always refers to the element to which the event handler has been attached, as opposed to Event.target, which identifies the element on which the event occurred and which may be its descendant.
> [Event.currentTarget - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget)

**Comment by andrewculver** [comment]
@tleish I actually don't know offhand why it got implemented that way, but if you submit a PR that fixes your issue, I'll take it for a regression spin on our end and merge it! Thank you so much for the detailed issue!
