### ISSUE TITLE
Adding assertion prompts no alert dialog and does not flush into test.

### ISSUE THREAD

**Issue by cheesam** [bullet-train-co/magic_test#19]
Attempting to add an assertion by highlight some text and pressing Control + Shift + A. I don't receive an alert dialogue confirming the assertion has been generated. Instead, nothing happens, and when I flush in the terminal nothing is recorded.

If someone could suggest how I can debug this. Console in chrome is recording nothing but errors:
sign_in:192 Uncaught TypeError: Cannot read property 'observe' of undefined
    at mutationStart (sign_in:192)
    at HTMLDocument.<anonymous> (sign_in:338)
    
I'm attempting to assert the sign in flash error is there as in the demonstration on Twitter, I am using Devise.

**Comment by andrewculver** [comment]
@cheesam Hey, sorry you're having trouble, but thanks for writing up an issue! What about regular form field stuff? Was that able to record and flush out?

**Comment by tleish** [comment]
@cheesam - what browser were you using?

My guess is this PR #22 will resolve the bug.

**Comment by andrewculver** [comment]
@cheesam Sorry, didn't mean to automatically close this issue. Can you try:

```
gem 'magic_test', github: 'bullet-train-co/magic_test', branch: 'main'
```

Then do `bundle install` and see whether your issue is resolved? 🙏

**Comment by cheesam** [comment]
Thank you @andrewculver. I've edited the Gemfile with the recommended line and commented out the previous one.

I've run `bundle install`. Bundle has returned `Using magic_test 0.0.6 (was 0.0.4) from https://github.com/bullet-train-co/magic_test.git (at main@1c44e38)`

Now when I attempt to run `MAGIC_TEST=1 rails test:system test/system/basics_test.rb`, the terminal returns `NoMethodError: undefined method `jquery_already_included=' for MagicTest:Module`.

**Comment by andrewculver** [comment]
@cheesam Yes, sorry, broke that [in 0.0.5](https://github.com/bullet-train-co/magic_test/releases). You need to remove `config/initializers/magic_test.rb` from your project.

**Comment by cheesam** [comment]
@andrewculver I can now confirm that I'm experiencing the desired behaviour, in addition `'click_on'` is now included where it wasn't previously.

Thanks for the assist in getting me up and running and thanks for making such a great gem.

**Comment by andrewculver** [comment]
@cheesam So glad it's working for you!
@tleish Thanks for your help with this one!
