### ISSUE TITLE
Support RSpec expectations syntax

### ISSUE THREAD

**Issue by rubendinho** [bullet-train-co/magic_test#24]
When generating assertions in the browser, the inserted assertions follow the `assert` syntax like so: 

`assert page.has_content? 'Foo'`

It would be great to support the following syntax: 

`expect(page).to have_content 'Foo'`

This seems like it should be triggered by a global setting somewhere.

**Comment by andrewculver** [comment]
@rubendinho Yup, I like that. For anyone who wants to tackle this, there is an example of how we previously had configuration values in `config/initializers/magic_test.rb` (which we removed) in [this PR](https://github.com/bullet-train-co/magic_test/pull/13/files).

**Comment by tleish** [comment]
Instead of a config, could you auto-detect this with something like:

```ruby
if defined? RSpec
  # RSpec code
else
  # Minitest code
end
```
