### ISSUE TITLE
Add Javascript tags in layouts through generator

### ISSUE THREAD

**Issue by bear-in-mind** [bullet-train-co/magic_test#25]
Hey there ! Congrats on your amazing work. Would you be interested in having your install generator add the required line in the layouts headers ? I'm currently doing a similar thing for a [project of mine](https://github.com/bear-in-mind/abyme) (PR still in progress).

**Comment by andrewculver** [comment]
@bear-in-mind Absolutely! Would appreciate this very much if you can hack it! 🙏

**Comment by gazayas** [comment]
https://github.com/bullet-train-co/magic_test/blob/b086d2f9bdfcbbe1b3d5283fa10fd5877f73256b/lib/generators/magic_test/install_generator.rb#L47-L53

We added the logic to add the `render 'magic_test/support'` line to add all of the JavaScript here:
- https://github.com/bullet-train-co/magic_test/pull/76
