### ISSUE TITLE
Support for RSpec?

### ISSUE THREAD

**Issue by coorasse** [bullet-train-co/magic_test#3]
What about support for RSpec?
I quickly tried it and I noticed the following:

## I had to include `include MagicTest::Support` in my test file
Maybe a bit annoying since I want it only while writing them, and remove it afterwards, still I might have it always included in `spec/rails_helper.rb`.

## If I run the system test on rack_test (default if I do not specify `:js` in my test) it fails
Maybe relevant also on minitest. You simply get:

```  
Capybara::NotSupportedByDriverError:
   Capybara::Driver::Base#evaluate_script
```

which forces you to open the implementation to understand that you are not using a selenium driver (if you are dumb like me). Maybe it can be intercepted and write something like "Hey! You need a browser to use magic_test!"

## `pry` as a dependency
I didn't have it for `group: :test`. should it be a dependency?

## `ok` not working
After solving all the above, I ended up with:

```
NoMethodError: undefined method `split' for nil:NilClass
from /Users/coorasse/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/magic_test-0.0.3/lib/magic_test/support.rb:67:in `ok'
```

since it actually looks for a `test` folder. Maybe we could start from here? `caller.select { |s| s.include?("/test/") || s.include?("/spec/") }` seems to return me already the file I am looking for.

**Comment by andrewculver** [comment]
@coorasse This is all great feedback. Thanks for taking time to write it all up. I've separated each of them into separate issues at #4 #5 #6 #7.
