### ISSUE TITLE
Selenium::WebDriver::Error::JavascriptError: SecurityError: The operation is insecure thrown in firefox

### ISSUE THREAD

**Issue by ayushn21** [bullet-train-co/magic_test#33]
I've suddenly started getting the below error when I invoke `magic_test` in Firefox.

`Selenium::WebDriver::Error::JavascriptError: SecurityError: The operation is insecure.`

It fails in Chrome as well but with a completely different error:

```
Selenium::WebDriver::Error::WebDriverError: <unknown>: Failed to read the 'sessionStorage' property from 'Window': Storage is disabled inside 'data:' URLs.
  (Session info: chrome=89.0.4389.114)
```

No idea what's going on here. I'd appreciate any help!

Ruby version: 2.7.2
Rails version: 6.1.3.1
Magic Test version: 0.0.6

Thanks!

**Comment by ayushn21** [comment]
Ok this is completely magically stopped happening. I'm utterly confused but closing for now ....

**Comment by chrisortman** [comment]
Just happened to me, did you by chance call magic test before you visit or opened any pages in the browser? That was my issue.

**Comment by ayushn21** [comment]
Yup that's exactly what the problem was. Got to the bottom of it several days after opening/closing this issue haha.
