### ISSUE TITLE
RSpec: "I had to include include MagicTest::Support in my test file"

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/magic_test#4]
From #3: 

> Maybe a bit annoying since I want it only while writing them, and remove it afterwards, still I might have it always included in `spec/rails_helper.rb`.

**Comment by andrewculver** [comment]
@coorasse We should be able to fix this in https://github.com/bullet-train-co/magic_test/blob/main/lib/magic_test/engine.rb . Need to figure out what the appropriate parent class is in RSpec.

**Comment by andrewculver** [comment]
@coorasse Do you know which RSpec parent class I can include `MagicTest::Support` into automatically? If you don't know off-hand, can you throw an exception in one of your tests and send me the stack trace? That would help.

**Comment by rubendinho** [comment]
I think `rails_helper.rb` is the most common file to include modules in, but I don't believe there's any real consensus. People use `rails_helper.rb` or `spec_helper.rb` in my experience.  We actually use a `system_helper.rb` which is required before any system spec, and here's roughly how it looks: 

```ruby
RSpec.configure do |config|
  config.include MagicTest::Support, js: true
  
  # Drive tests with the faster rack_test driver if we don't need Javascript
  config.before(:each, type: :system) do
    driven_by :rack_test
  end

  # Drives tests with Selenium if we need Javascript
  config.before(:each, type: :system, js: true) do
    if ENV['MAGIC_TEST']
      driven_by :selenium, using: :chrome, screen_size: [1400, 1400]
    else
      driven_by :selenium_chrome_headless
    end
    ActionDispatch::SystemTesting::Server.silence_puma = false
  end
end
```

**Comment by andrewculver** [comment]
@rubendinho Thank you so much for that context! I've pushed up a PR that I hope fixes this issue, but I'll need someone else to take it for a spin. We'll definitely have to add a more robust guide on how to educate people on getting their browser vs. rack_test vs. headless browser stuff configured properly.
