### ISSUE TITLE
"pry as a dependency"

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/magic_test#6]
From #3: 

> I didn't have it for `group: :test`. should it be a dependency?

**Comment by andrewculver** [comment]
@coorasse We've got `spec.add_dependency "pry"` [in the gemspec]()https://github.com/bullet-train-co/magic_test/blob/5921866f83b808b091555b5c847dc32165e39652/magic_test.gemspec#L28. Is there a better way to specify this?

**Comment by coorasse** [comment]
That's pretty weird. Yes, I see that. let me do some more tests and come back to you with more information

**Comment by coorasse** [comment]
If I don't have it in my Gemfile I get:

```
     NoMethodError:
       undefined method `pry' for #<Binding:0x00007fbc2fa631f8>
```

I am not really sure why. I'd have expected it to be required automatically... :thinking:

Still, If I require it manually with `require 'pry'`, then it works even if I don't include it in the Gemfile:thinking: which means that is added by `magic_test` but not required?
