### ISSUE TITLE
RSpec: "`ok` not working"

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/magic_test#7]
From #3:

> After solving all the above, I ended up with:
>
> ```
> NoMethodError: undefined method `split' for nil:NilClass
> from /Users/coorasse/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/magic_test-0.0.3/lib/magic_test/support.rb:67:in `ok'
> ```
> 
> since it actually looks for a `test` folder. Maybe we could start from here? `caller.select { |s| s.include?("/test/") || s.include?("/spec/") }` seems to return me already the file I am looking for.

**Comment by andrewculver** [comment]
@coorasse That fix looks like it'll work. Giving it a shot.

**Comment by coorasse** [comment]
Yes. It's working for me 👍
