### ISSUE TITLE
Version 0.1.0 is not published on ruby gems

### ISSUE THREAD

**Issue by adrienpoly** [bullet-train-co/magic_test#88]
Hello

Thanks for your work on this gem. 
I noticed that v0.1.0 was released on Github but I think it was not published to Rubygems

as a solution, I am currently pointing to GitHub 

```ruby
gem "magic_test", git: "https://github.com/bullet-train-co/magic_test.git", tag: 'v0.1.0'
```

thanks

**Comment by kg-currenxie** [comment]
Thx. Would be nice to release to rubygems. 
It took a while to figure out, as the current docs with `bundle binstubs magic_test` does not work in 0.0.9

**Comment by gazayas** [comment]
@kg-currenxie Same here, wasn't able to run `bundle binstubs magic_test` until I used `gem "magic_test", git: "https://github.com/bullet-train-co/magic_test.git", tag: 'v0.1.0'`

**Comment by Frexuz** [comment]
Any news? Running bundle install is always slow as github sources dont cache. Even more so when travelling without a good connection

**Comment by gazayas** [comment]
Tagging @andrewculver just in case

**Comment by Frexuz** [comment]
Bump :(

**Comment by jagthedrummer** [comment]
@andrewculver If you'll make me an owner on this gem I'll get a new release cut and published.

**Comment by gazayas** [comment]
As a side note, this doesn't solve the rubygems issue, but I at least started my own fork which includes some of the pull requests I have open on this repository.

Feel free to open PRs over there in the meantime.

```ruby
gem "magic_test", git: "git@github.com:gazayas/magic_test.git", branch: "pre-0.1.0"
```

**Comment by konung** [comment]
> @kg-currenxie Same here, wasn't able to run `bundle binstubs magic_test` until I used `gem "magic_test", git: "https://github.com/bullet-train-co/magic_test.git", tag: 'v0.1.0'`

Yep. Same issue. Makes Installation instructions confusing - as this line about `bundle binstubs` doesn't work 

```bash

bundle binstubs magic_test                                                                          
magic_test has no executables, but you may want one from a gem it depends on.
  pry has: pry
  
  ```
  
  But pointint to git / tag v0.1.0 - worked.

**Comment by natevick** [comment]
👋🏻 I just pushed version 0.1.0 to Rubygems.

**Comment by kg-currenxie** [comment]
Thank you!
